- charset="utf-8"
- http-equiv="X-UA-Compatible" content="IE=edge"
- name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1"
- name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1"
- name="author" content="Constellation Design"
  # keywords
- name="keywords" content="UX Design, Amsterdam, Product design, contractor, consultancy, consultant, design, workshop, design sprint, UI Design, mobile design, ux research, reduce risk, maximize opportunity, diverse, cultural, challenge, urban, modern, agile, efficient, small, local, curious, patient"
# Favicon support
- name="msapplication-TileColor" content="#ffffff"
- name="msapplication-TileImage" content="/assets/images/ms-icon-144x144.png"
- name="theme-color" content="#ffffff"